In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/Product_Dataset.csv")

In [3]:
df.head()

,Order_ID,Customer_ID,Order_Date,Product_ID,Product_Name,Category,Brand,Region,State,City,Quantity,Unit_Price,Discount_Pct,Sales,Cost_Price,Profit,Inventory_Level,Customer_Rating,Return_Flag,Sales_Channel
0,O00001,C075,2025-03-29,P007,Dining Table,Home,Ikea,East,West Bengal,Kolkata,8,3972,20,25420.80,18716.21,6704.59,372,4,No,Store
1,O00002,C076,2025-11-10,P022,Football,Sports,Nike,North,UP,Noida,8,2633,15,17904.40,12551.01,5353.39,21,5,No,Online
2,O00003,C003,2025-11-03,P010,Mattress,Home,Sleepwell,East,Odisha,Bhubaneswar,3,2099,15,5352.45,4395.96,956.49,134,5,No,App
3,O00004,C002,2025-12-06,P004,Headphones,Electronics,Sony,North,UP,Noida,2,2241,0,4482.00,2482.99,1999.01,91,4,No,Online
4,O00005,C002,2025-02-23,P008,Mixer,Home,Philips,West,Maharashtra,Mumbai,1,2155,5,2047.25,1542.18,505.07,105,4,No,Store

In [3]:
df.shape

(2000, 20)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         2000 non-null   object
 1   Customer_ID      2000 non-null   object
 2   Order_Date       2000 non-null   object
 3   Product_ID       2000 non-null   object
 4   Product_Name     2000 non-null   object
 5   Category         2000 non-null   object
 6   Brand            2000 non-null   object
 7   Region           2000 non-null   object
 8   State            2000 non-null   object
 9   City             2000 non-null   object
 10  Quantity         2000 non-null   int64
 11  Unit_Price       2000 non-null   int64
 12  Discount_Pct     2000 non-null   int64
 13  Sales            2000 non-null   float64
 14  Cost_Price       2000 non-null   float64
 15  Profit           2000 non-null   float64
 16  Inventory_Level  2000 non-null   int64
 17  Customer_Rating  2000 non-null   int64
 18  Return_Flag      2000 non-null   object
 19  Sales_Channel    2000 non-null   object
dtypes: float64(3), int64(5), object(12)
memory usage: 312.6+ KB

In [9]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [11]:
df.dtypes

Order_ID                   object
Customer_ID                object
Order_Date         datetime64[ns]
Product_ID                 object
Product_Name               object
Category                   object
Brand                      object
Region                     object
State                      object
City                       object
Quantity                    int64
Unit_Price                  int64
Discount_Pct                int64
Sales                     float64
Cost_Price                float64
Profit                    float64
Inventory_Level             int64
Customer_Rating             int64
Return_Flag                object
Sales_Channel              object
dtype: object

In [5]:
df.duplicated().sum()

np.int64(0)

In [14]:
def check_missing_values(df):
    return df.isnull().sum()

In [15]:
check_missing_values(df)

Order_ID           0
Customer_ID        0
Order_Date         0
Product_ID         0
Product_Name       0
Category           0
Brand              0
Region             0
State              0
City               0
Quantity           0
Unit_Price         0
Discount_Pct       0
Sales              0
Cost_Price         0
Profit             0
Inventory_Level    0
Customer_Rating    0
Return_Flag        0
Sales_Channel      0
dtype: int64

In [4]:
def calculate_kpis(df):

    return {}

df.groupby("Sales_Channel")["Sales"].sum()

Sales_Channel
App       8367455.00
Online    8619838.15
Store     8316427.50
Name: Sales, dtype: float64

In [10]:
monthly_summary = (df.groupby(df["Order_Date"].dt.to_period("M")).agg(
          Total_Revenue = ("Sales","sum"),
          Total_Profit = ("Profit","sum"),
          Total_Quantity = ("Quantity","sum"))).reset_index()
monthly_summary.head()

  Order_Date  Total_Revenue  Total_Profit  Total_Quantity
0    2025-01     1787458.00     445181.58             792
1    2025-02     1566925.65     411100.20             770
2    2025-03     2385156.90     632001.45            1009
3    2025-04     2185507.95     541600.05             926
4    2025-05     2374214.10     625484.54            1033